name: map_address_picker
description: A simple flutter plugin for picking users location using google maps.
version: 0.3.0
homepage: https://github.com/athul-ain/map_address_picker

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.1.1
  geolocator: ^8.0.5
  google_maps_flutter_platform_interface: ^2.1.5
  geolocator_platform_interface: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter: