on:
  push:
    tags:
      - '*'

name: Test, Build and Release apk
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: actions/setup-java@v3.1.1
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2.4.0
      with:
        flutter-version: '2.10.1'
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk --debug --split-per-abi
    - run: flutter build appbundle

    - name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1
   
    - name: Create a Release APK
      uses: ncipollo/release-action@v1
      with:
        tag: ${{steps.tag.outputs.tag}}
        artifacts: "build/app/outputs/apk/debug/*.apk"
        token: ${{ secrets.TOKEN }}
